### ISSUE TITLE
It seems that the main.py file is empty.

### ISSUE THREAD

**Issue by ansucatherine** [Guanzhou-Ke/cloven#1]
Hi! I read this paper on arxiv and found it quite inspiring for me. I tried to train the model by running `python main.py -f <path to your config>` as suggested in the readme file, but found main.py is an empty file. Could you please upload an available one? It would be really helpful!

**Comment by Guanzhou-Ke** [comment]
The `main.py` and `trainer.py` are empty because of the paper is under peer reviewing. BUT now, we have uploaded the full version `main.py` and `trainer.py` into the repos. Thank you for your attention.
