### ISSUE TITLE
Missing vis_result.py file

### ISSUE THREAD

**Issue by Yangyya9** [Guanzhou-Ke/cloven#2]
In the trainer.py file, from vis_result import vis_hidden4training，
Problem encountered: Unresolved reference 'vis_result' and Unresolved reference 'vis_hidden4training'.
May I ask if file vis_result.py is missing? Can it be completed? Thank you very much

**Comment by Yangyya9** [comment]
@Guanzhou-Ke,Can you please complete it? Thank you very much.

**Comment by Guanzhou-Ke** [comment]
Hey, The file `vis_result` is used to record the latent representations during the training process for my local testing. The training would be OK whether you used the `record_embedding` function. That's to say, you can directly remove these related functions.

In addition, `vis_hidden4training` just uses the `TSNE` function, implemented by Sklearn, to compress the latent representation into 2-dimensional vectors. If you want to record the latent changes in your training process, you could easily implement them. But this operation would consume a lot of CPU resources. I'd like to remove it in the next version.

Last but not least, thank you so much for improving our work.

**Comment by Yangyya9** [comment]
Thank you very much.
