### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by Yangyya9** [Guanzhou-Ke/cloven#3]
Hello, running main.py directly resulted in the following error. How can I modify it.
TypeError: expected str, bytes or os.PathLike object, not NoneType
debug path：
1、def main():
    # Load arguments.
    args = parse_args()
    config = get_cfg(args)   

2、def get_cfg(args):
    """Initialize configuration.
    """
    config = get_cfg_defaults()
    config.merge_from_file(args.file)

3、    def merge_from_file(self, cfg_filename):
        """Load a yaml config file and merge it this CfgNode."""
        with open(cfg_filename, "r") as f:    #The problem lies in this line
            cfg = self.load_cfg(f)
        self.merge_from_other_cfg(cfg)
I tried to write the path, but there was still a problem. Could you please guide me to make the necessary modifications? Thank you very much.

**Comment by Yangyya9** [comment]
@Guanzhou-Ke Can you provide an answer? Thank you very much.

**Comment by Guanzhou-Ke** [comment]
May be you could check your OS.- In this project, linux- style path is OK.
